name: Send a Tweet

on:
  push:
    branches: [ tweet ]
  pull_request:
    branches: [ tweet ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: log
        run: |
          POST_COMMIT_MESSAGE=$(git log --no-merges -1 --pretty=%B)
          echo ::set-output name=POST_COMMIT_MESSAGE::$POST_COMMIT_MESSAGE
          if [ $POST_COMMIT_MESSAGE == *"Tweet: "* ]; then HAS_TWEET='true' ; fi
          echo ::set-output name=HAS_TWEET=$HAS_TWEET
        
      - id: parse
        if: ${{ steps.vars.outputs.HAS_TWEET }}
        run: |
          searchString="Tweet: "
          POST_COMMIT_MESSAGE=${{ steps.vars.outputs.POST_COMMIT_MESSAGE }}
          tweet=${POST_COMMIT_MESSAGE#*$searchString}
          echo ::set-output name=TWEET=$tweet

      - uses: ethomson/send-tweet-action@v1
        if: ${{ steps.vars.outputs.HAS_TWEET }}
        with:
          status: "${{ steps.vars.outputs.TWEET }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
