name: Send a Tweet

on:
  push:
    branches: [ tweet ]
  pull_request:
    branches: [ tweet ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: log
        run: |
          POST_COMMIT_MESSAGE=$(git log --no-merges -1 --pretty=%B)
          echo "POST_COMMIT_MESSAGE=$POST_COMMIT_MESSAGE" >> $GITHUB_ENV
          if [$POST_COMMIT_MESSAGE == *"Tweet: "*]; then HAS_TWEET='true' ; fi
          echo "HAS_TWEET=$HAS_TWEET" >> $GITHUB_ENV
        
      - id: parse
        if: $HAS_TWEET
        run: |
          searchString="Tweet: "
          tweet=${POST_COMMIT_MESSAGE#*$searchString}
          echo "TWEET=$tweet" >> $GITHUB_ENV

      - uses: ethomson/send-tweet-action@v1
        if: HAS_TWEET
        with:
          status: "$TWEET"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
